### ISSUE TITLE
Your URL didn't respond with the value of the challenge parameter.

### ISSUE THREAD

**Issue by debosmit-git** [jonchurch/slack-telegram-connector#2]
Hmm, our verification request timed out before we received a response. Try again?

We’ll send HTTP POST requests to this URL when events occur. As soon as you enter a URL, we’ll send a request with a challenge parameter, and your endpoint must respond with the challenge value. https://api.slack.com/events/url_verification

**Comment by debosmit-git** [comment]
Gltich Error Log
```
at module.exports (/app/skills/test.js:2:24)
at /app/bot.js:57:30
    at Array.forEach (<anonymous>)
at Object.<anonymous> (/app/bot.js:56:43)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
Initializing Botkit v0.0.1
info: ** No persistent storage method specified! Data may be lost when process shuts down.
debug: Setting up a handler for spawned
debug: Setting up a handler for heard_trigger
debug: Setting up a handler for command_triggered
debug: Setting up a handler for remote_command_end
Initializing Botkit v0.0.1
info: ** Using simple storage. Saving data to ./.data/
debug: Setting up a handler for spawned
debug: Setting up a handler for heard_trigger
debug: Setting up a handler for command_triggered
debug: Setting up a handler for remote_command_end
info: ** Setting up custom handlers for processing Slack messages
debug: Setting up a handler for message_received
debug: Setting up a handler for oauth:success
debug: Setting up a handler for create_team
debug: Setting up a handler for update_team
setup webhooks!
/app/lib/Slackbot_worker.js:41
            throw new Error('No incoming webhook URL specified!');
            ^
Error: No incoming webhook URL specified!
at Object.bot.configureIncomingWebhook (/app/lib/Slackbot_worker.js:41:19)
at new module.exports (/app/lib/Slackbot_worker.js:756:13)
at Object.Botkit.botkit.spawn (/app/lib/CoreBot.js:1086:22)
at module.exports (/app/skills/test.js:2:24)
at /app/bot.js:57:30
    at Array.forEach (<anonymous>)
at Object.<anonymous> (/app/bot.js:56:43)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

```
